#!/bin/bash

# =========================================================
# Project: Debian/UGOS IPv6 Fixed Suffix Installer
# Author: Molirain
# Description: Fixes IPv6 suffix, solves Docker RA issues,
#              and persists across system updates.
# =========================================================

# 颜色配置
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${GREEN}=== IPv6 固定后缀 & Docker RA 修复工具 ===${NC}"

# --- 1. 环境检测 ---
if [ "$(id -u)" != "0" ]; then
   echo -e "${RED}错误: 请使用 root 权限运行此脚本 (sudo bash install.sh)${NC}"
   exit 1
fi

# 自动检测网卡 (优先检测 eth0 和 enp* 系列)
TARGET_IFACE=$(ip -o link show | awk -F': ' '{print $2}' | grep -E '^(eth|enp|eno)' | head -n 1)

if [ -z "$TARGET_IFACE" ]; then
    echo -e "${RED}未检测到常见网卡，请手动输入网卡名称:${NC}"
    read -p "网卡名称: " TARGET_IFACE
else
    echo -e "检测到网卡: ${YELLOW}${TARGET_IFACE}${NC}"
    read -p "确认使用此网卡? [y/N] " confirm
    if [[ "$confirm" != "y" && "$confirm" != "Y" ]]; then
        read -p "请输入网卡名称: " TARGET_IFACE
    fi
fi

# --- 2. 配置后缀 ---
TOKEN_FILE="/etc/ipv6_token.txt"

if [ -f "$TOKEN_FILE" ]; then
    CURRENT_SUFFIX=$(cat "$TOKEN_FILE")
    echo -e "发现现有配置后缀: ${GREEN}${CURRENT_SUFFIX}${NC}"
    read -p "是否保留此后缀? [Y/n] " keep
    if [[ "$keep" == "n" || "$keep" == "N" ]]; then
        read -p "请输入新的 4 位后缀 (如 1f67): " NEW_SUFFIX
        echo "$NEW_SUFFIX" > "$TOKEN_FILE"
    fi
else
    echo -e "${YELLOW}未找到配置文件 (可能是首次安装或系统已重置)${NC}"
    while [ -z "$SUFFIX_INPUT" ]; do
        read -p "请输入你要固定的 4 位后缀 (例如 1f67): " SUFFIX_INPUT
    done
    echo "$SUFFIX_INPUT" > "$TOKEN_FILE"
fi
chmod 644 "$TOKEN_FILE"

# --- 3. 写入核心脚本 ---
BIN_PATH="/usr/local/bin/gen-ipv6-token.sh"
echo "正在写入执行脚本..."

cat << EOF > "$BIN_PATH"
#!/bin/bash
# Auto-generated by install.sh

IFACE="${TARGET_IFACE}"
TOKEN_FILE="${TOKEN_FILE}"

if [ ! -f "\$TOKEN_FILE" ]; then exit 0; fi
SUFFIX=\$(cat "\$TOKEN_FILE" | tr -d ' \n\r')
if [ -z "\$SUFFIX" ]; then exit 0; fi

# 1. 强制开启 RA (修复 Docker 环境下的 IPv6)
sysctl -w net.ipv6.conf.\$IFACE.accept_ra=2 >/dev/null
sysctl -w net.ipv6.conf.\$IFACE.autoconf=1 >/dev/null

# 2. 生成随机中间段
R1=\$(od -An -N2 -t x2 /dev/urandom | tr -d ' ')
R2=\$(od -An -N2 -t x2 /dev/urandom | tr -d ' ')
R3=\$(od -An -N2 -t x2 /dev/urandom | tr -d ' ')

FULL_TOKEN="::\$R1:\$R2:\$R3:\$SUFFIX"

# 3. 写入内核 Token
ip token set "\$FULL_TOKEN" dev \$IFACE

# 4. 刷新生效 (兜底逻辑)
if [ -w /proc/sys/net/ipv6/conf/\$IFACE/disable_ipv6 ]; then
    echo 1 > /proc/sys/net/ipv6/conf/\$IFACE/disable_ipv6
    echo 0 > /proc/sys/net/ipv6/conf/\$IFACE/disable_ipv6
fi
EOF

chmod +x "$BIN_PATH"

# --- 4. 配置 Systemd 服务 ---
SERVICE_FILE="/etc/systemd/system/ipv6-fixed-token.service"
echo "正在配置 Systemd 服务..."

cat << EOF > "$SERVICE_FILE"
[Unit]
Description=Set IPv6 Fixed Suffix Token
After=network.target network-online.target
Wants=network-online.target

[Service]
Type=oneshot
ExecStart=${BIN_PATH}
RemainAfterExit=yes
User=root

[Install]
WantedBy=multi-user.target
EOF

# --- 5. 启动与验证 ---
echo "正在启动服务..."
systemctl daemon-reload
systemctl enable ipv6-fixed-token.service >/dev/null 2>&1
systemctl restart ipv6-fixed-token.service

echo -e "${GREEN}安装完成!${NC}"
echo "--------------------------------"
echo "当前 IPv6 地址:"
ip -6 addr show dev ${TARGET_IFACE} | grep inet6 | grep global
echo "--------------------------------"
echo -e "提示: 如果下次系统更新导致配置丢失，请重新运行此脚本即可一键恢复。"
